name: MyAutoTask

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # 修改：v3 -> v4

      - name: Set up Python
        uses: actions/setup-python@v5 # 修改：v4 -> v5
        with:
          python-version: '3.11'

      - name: Install Chinese Fonts (Full Support)
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-wqy-microhei fonts-wqy-zenhei xfonts-wqy

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run my script
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }} 
          PASSWORD: ${{ secrets.PASSWORD }} 
        run: python main.py

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4 # v4 已兼容 Node 24，保持不变即可
        with:
          name: debug-screenshots
          path: "**/*.png"
          retention-days: 5
